# Publish skilio to NPM manually

name: üö≤ Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      parameters:
        description: 'ü§î no param'
        required: false

permissions:
  contents: write
  pull-requests: read

# Do not allow multiple deployments simultaneously;
# skip non-running, non-latest queue runs, and do not cancel running workflows
concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: üîß Setup pnpm # Setup pnpm
        run: npm install -g pnpm
      - name: üì¶ Install dependencies
        run: pnpm i
      - name: üèó Build & Test
        run: pnpm run test
      - name: üöÄ Publish Package
        run: npm publish --provenance --access public
        if: | # Only publish under Moushudyx/skilio to prevent accidental publishes from forks
          startsWith(github.repository, 'Moushudyx')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: üîé Detect version # Get version from package.json
        id: version_check
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
      - name: üìù Generate release notes
        id: changelog
        run: |
          # Extract content under the first level 2 heading in CHANGELOG.md
          awk '
          /^## / && !found {
            found=1;
            next
          }
          found && /^#/ {
            exit
          }
          found' CHANGELOG.md > release_notes.txt

          # YYYY-MM-DD
          DATE=$(date +'%Y-%m-%d')

          # Output
          echo "release_title=Version ${{ steps.version_check.outputs.version }} - $DATE" >> $GITHUB_OUTPUT
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat release_notes.txt)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # echo "release_notes=$(cat release_notes.txt)" >> $GITHUB_OUTPUT
          echo "Version ${{ steps.version_check.outputs.version }} - $DATE"
          echo "$(cat release_notes.txt)"
      - name: üöÄ Create GitHub Release # Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version_check.outputs.version }}
          name: ${{ steps.changelog.outputs.release_title }}
          body: ${{ steps.changelog.outputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: ‚òÇÔ∏è Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
